apiVersion: v1
kind: Service
metadata:
  name: dns-svc-lb
  annotations:
    metallb.universe.tf/loadBalancerIPs: 172.17.255.10
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: dns-tcp
  - protocol: UDP
    port: 80
    targetPort: 8000
    name: dns-udp
