apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-pv-1
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "yc-network-hdd"
  csi:
    driver: disk-csi-driver.mks.ycloud.io
    fsType: ext4
    volumeHandle: fhm545aslg8euhkj1544
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-pv-2
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "yc-network-hdd"
  csi:
    driver: disk-csi-driver.mks.ycloud.io
    fsType: ext4
    volumeHandle: fhm545aslg8euhkj1544
  volumeMode: Filesystem
