apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loadgenerator
  namespace: microservices-demo
spec:
  interval: 1m
  chart:
    spec:
      chart: ./deploy/charts/loadgenerator
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    image:
      tag: v0.0.9 # {"$imagepolicy": "microservices-demo:loadgenerator:tag"}
