---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: adservice
  namespace: microservices-demo
spec:
  image: tippman/adservice
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: adservice
  namespace: microservices-demo
spec:
  imageRepositoryRef:
    name: adservice
    namespace: microservices-demo
  policy:
    semver:
      range: '>=0.0.2'
