kind: Service
apiVersion: v1
metadata:
  name: nginx-svc
  labels:
    app: web
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 80