apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-stub-status-config
data:
  stub-status.conf: |
    server {
      listen 80;
      server_name localhost;
      location /basic_status {
        stub_status;
      }
    }