apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: server
          image: tippman/hipster-shop-paymentservice:v0.0.2
          env:
            - name: PORT
              value: "50051"
            - name: DISABLE_PROFILER
              value: "1"